Fix AttributeError in outsample evaluation
- Store baseline_models as instance variable in BaselineModelTrainer
- Clone models from baseline_models for outsample evaluation
- Remove incorrect access to cv_result.model (which doesn't exist)

The CrossValidationResult doesn't store the trained model by default,
so we need to clone from the original model configuration instead.

Fixes error: AttributeError: 'CrossValidationResult' object has no attribute 'model'